server:
  port: 9002

spring:
  application:
    name: nacos-payment-service
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 172.16.103.10:1111
management:
  endpoints:
    web:
      exposure:
        include: "*"
